-- End-to-end: load Gen151 through the engine's OWN headless loader, against
-- a Red-, Blue- and Yellow-shaped dataset, and assert its stated effect
-- (SPEC 9; CONTRIBUTING-mods.md Route A).
--
-- Run it from the engine checkout, because tests.modkit's package.path and
-- the SDK's filesystem root are both relative to the working directory:
--
--   cd /path/to/gen1recomp
--   GEN151=/path/to/Gen151 lua "$GEN151/tests/mod_load_test.lua"
--
-- The datasets come from tests/fixtures/vanilla.lua, generated by
-- tools/gapset.py out of the pret disassembly, so "no vanilla slot changed"
-- is checked against the real Kanto tables rather than against a toy.

local GEN151 = os.getenv("GEN151") or "../Gen151"

-- LuaJIT's default package.path has no "?/init.lua" arm, which is the one
-- tests.modkit lives behind; the harness adds it too, but only once it has
-- been reached.
if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?.lua;./?/init.lua;" .. package.path
end

local T = require("tests.modkit")
local check, eq = T.check, T.eq

local vanilla = assert(loadfile(GEN151 .. "/tests/fixtures/vanilla.lua"))()

-- Both engine screens, held from before anything loads.  This mod used to
-- wrap them and never unwrap them, which is right in a game (one load per
-- process) and inconvenient in a suite that loads several times; it does not
-- wrap either any more, and these two are what says so.
local PRISTINE_DEX_NEW = require("src.ui.PokedexMenu").new
local PRISTINE_TOWNMAP_NEW = require("src.ui.TownMap").new

local function deepCopy(value)
  if type(value) ~= "table" then return value end
  local copy = {}
  for k, v in pairs(value) do copy[k] = deepCopy(v) end
  return copy
end

-- A dataset shaped like the cartridge: the fixture's own tables, with Kanto's
-- encounters, species and Super Rod groups written over them.  Everything
-- else (items, text, constants, the seeded field defaults) stays the
-- fixture's, which is what keeps this ROM-free.
local function datasetFor(version)
  local data = T.fixtures.fresh()
  local source = vanilla.versions[version]
  data.encounters = deepCopy(source.encounters)
  -- The fixture's own three mons carry dex numbers 1-3, which collide with
  -- Bulbasaur, Ivysaur and Venusaur; PokedexMenu keys by dex number, so
  -- whichever pairs() reached last would own the row.  Kanto owns the
  -- numbering here.
  for _, def in pairs(data.pokemon) do def.dex = nil end
  for id, def in pairs(source.pokemon) do
    data.pokemon[id] = deepCopy(def)
  end
  data.field.superRod = deepCopy(source.superRod)
  return data
end

-- Loader:_discover hard-codes the "mods" root, so the SDK aliases a real
-- directory onto it.  Two adjustments here:
--
--   * the SDK's filesystem joins its root onto every path, so an absolute mod
--     directory needs an empty root rather than the default "."
--   * `write` is dropped.  The loader persists mod enable state and the option
--     schema snapshot through the same filesystem, and with an absolute root
--     those land at / -- the loader already treats a write-less fs as
--     "in-memory only", which is what a test wants anyway.
local ROOT = GEN151:sub(1, 1) == "/" and "" or "."

-- `overrides` serves synthetic files ahead of the real ones, which is how the
-- option-state cases below hand the loader a pre-set options.lua without
-- writing one to disk.
local function readOnlyAlias(paths, overrides)
  local inner = T.fs.new(ROOT)
  overrides = overrides or {}
  -- An empty options file by default: without one the loader's recovery path
  -- prints a "missing; recovered from tmp copy" line per load, which is noise
  -- here and would drown a real warning.
  if overrides["options.lua"] == nil then
    overrides["options.lua"] = "return {}"
  end
  local alias = {}
  for _, path in ipairs(paths) do
    alias[(path:gsub("/+$", ""):match("[^/]+$"))] = path
  end
  local function map(path)
    if path == nil then return path end
    for name, real in pairs(alias) do
      local prefix = "mods/" .. name
      if path == prefix then return real end
      if path:sub(1, #prefix + 1) == prefix .. "/" then
        return real .. path:sub(#prefix + 1)
      end
    end
    return path
  end
  local loadstr = loadstring or load
  return {
    root = inner.root,
    read = function(path)
      if overrides[path] then return overrides[path] end
      return inner.read(map(path))
    end,
    load = function(path)
      if overrides[path] then return loadstr(overrides[path], path) end
      return inner.load(map(path))
    end,
    getInfo = function(path)
      if overrides[path] then return { type = "file" } end
      if path == "mods" then return { type = "directory" } end
      return inner.getInfo(map(path))
    end,
    getDirectoryItems = function(path)
      if path == "mods" then
        local names = {}
        for name in pairs(alias) do names[#names + 1] = name end
        table.sort(names)
        return names
      end
      return inner.getDirectoryItems(map(path))
    end,
  }
end

local function loadPaths(paths, data, overrides, dev)
  return T.sdk.loadMods(paths, { data = data, dev = dev,
                                 fs = readOnlyAlias(paths, overrides) })
end

local function loadGen151(data)
  local run = T.sdk.loadMods({ GEN151 }, { data = data,
                                           fs = readOnlyAlias({ GEN151 }) })
  run.mod = select(2, next(run.mods))
  return run
end

for _, version in ipairs({ "red", "blue", "yellow" }) do
  local before = deepCopy(vanilla.versions[version].encounters)
  local data = datasetFor(version)
  local run = loadGen151(data)

  eq(#run.errors, 0, version .. ": loads with no boot errors ("
    .. table.concat(run.errors, "; ") .. ")")
  check(run.mod ~= nil, version .. ": the mod was discovered")
  check(run.mod == nil or run.mod.failed ~= true,
    version .. ": the mod did not fail")

  local exports = run.loader.exports.gen151
  check(exports ~= nil, version .. ": exports are published")
  check(exports and exports.enabled == true,
    version .. ": the spawn layer ran")

  -- ---- prime directive 1: never overwrite a vanilla slot
  --
  -- Not the species, not the level, not the rate.  Checked on every map, for
  -- every slot, on all three versions.
  local drift = nil
  for mapId, record in pairs(before) do
    local after = data.encounters[mapId]
    if not after then
      drift = mapId .. " vanished from the table"
      break
    end
    for _, kind in ipairs({ "grass", "water" }) do
      local wasGroup, isGroup = record[kind], after[kind]
      if wasGroup then
        if not isGroup then
          drift = mapId .. "." .. kind .. " vanished"
          break
        end
        if wasGroup.rate ~= isGroup.rate then
          drift = ("%s.%s rate %s -> %s"):format(mapId, kind,
            tostring(wasGroup.rate), tostring(isGroup.rate))
          break
        end
        if isGroup.buckets ~= nil then
          drift = mapId .. "." .. kind .. " grew a buckets list"
          break
        end
        for i, slot in ipairs(wasGroup.slots) do
          local now = isGroup.slots[i]
          if not now or now.species ~= slot.species or now.level ~= slot.level then
            drift = ("%s.%s slot %d: %s L%s -> %s L%s"):format(mapId, kind, i,
              slot.species, tostring(slot.level),
              now and now.species or "nil", now and tostring(now.level) or "nil")
            break
          end
        end
        if #isGroup.slots < #wasGroup.slots then
          drift = mapId .. "." .. kind .. " lost slots"
        end
      end
      if drift then break end
    end
    if drift then break end
  end
  check(drift == nil, version .. ": no vanilla slot, level or rate changed: "
    .. tostring(drift))

  -- ---- prime directive 2: everything added is renewable, and reachable
  --
  -- Every species Gen151 places must land in a slot table or a Super Rod
  -- group -- never anywhere else -- and every row it applied must name a map
  -- that actually exists with a live rate.
  local placed = {}
  for _, row in ipairs(exports.rows or {}) do
    placed[row.species] = true
    local record = data.encounters[row.map]
    local group = record and record[row.method == "water" and "water" or "grass"]
    check(group ~= nil and (group.rate or 0) > 0,
      ("%s: %s is placed on %s.%s, which has no live rate"):format(
        version, row.species, row.map, row.method))
  end
  for _, row in ipairs(exports.fishing or {}) do
    placed[row.species] = true
    local groups = data.field.superRod or {}
    check(groups[row.map] ~= nil,
      ("%s: %s is placed on %s's SUPER ROD group, which does not exist")
        :format(version, row.species, row.map))
  end

  -- ---- the gap closes
  --
  -- Every species this version had no renewable source for is either placed,
  -- follows by evolution from something placed, reachable with the LINK
  -- CABLE, or a legendary Gen151 deliberately leaves alone.  MEW is placed
  -- too, now that its feature defaults on -- but behind a gate, so the check
  -- below still insists it is absent from the live table.
  local UNTOUCHED = { ARTICUNO = true, ZAPDOS = true, MOLTRES = true,
                      MEWTWO = true }
  local CABLE = { ALAKAZAM = true, MACHAMP = true, GOLEM = true,
                  GENGAR = true }
  -- Seed with what the cartridge already provides -- KADABRA, MACHOKE,
  -- GRAVELER and HAUNTER are all in the vanilla grass -- so the closure below
  -- can carry the LINK CABLE across them.
  local missing = {}
  for _, name in ipairs(vanilla.versions[version].missing) do
    missing[name] = true
  end
  local covered = {}
  for _, name in ipairs(vanilla.dex) do
    if not missing[name] then covered[name] = true end
  end
  for species in pairs(placed) do covered[species] = true end
  -- close over evolution the way the game does
  local changed = true
  while changed do
    changed = false
    for id, def in pairs(data.pokemon) do
      if covered[id] then
        for _, evo in ipairs(def.evolutions or {}) do
          if evo.species and not covered[evo.species]
             and (evo.method ~= "TRADE" or CABLE[evo.species]) then
            covered[evo.species] = true
            changed = true
          end
        end
      end
    end
  end
  local uncovered = {}
  for _, species in ipairs(vanilla.dex) do
    if missing[species] and not covered[species] and not UNTOUCHED[species] then
      uncovered[#uncovered + 1] = species
    end
  end
  eq(#uncovered, 0, version .. ": every gap is closed, but these are not: "
    .. table.concat(uncovered, ", "))

  -- ---- Mew is not in the table, and cannot be spoiled by AREA
  local mewSlot = nil
  for mapId, record in pairs(data.encounters) do
    for _, kind in ipairs({ "grass", "water" }) do
      for _, slot in ipairs((record[kind] or {}).slots or {}) do
        if slot.species == "MEW" then mewSlot = mapId .. "." .. kind end
      end
    end
  end
  check(mewSlot == nil,
    version .. ": MEW must not be in data.encounters before its gate: "
      .. tostring(mewSlot))

  -- ---- the LINK CABLE exists and is on the shelf it was promised on
  local cable = data.items and data.items.LINK_CABLE
  check(cable ~= nil, version .. ": LINK CABLE is registered")
  eq(cable and cable.price, 2100, version .. ": LINK CABLE costs the same as "
    .. "an evolution stone")
  local shelf = (data.text_pointers or {}).CeladonMart4F
  local clerk = shelf and shelf.TEXT_CELADONMART4F_CLERK
  local onShelf = false
  for _, id in ipairs((clerk or {}).mart or {}) do
    if id == "LINK_CABLE" then onShelf = true end
  end
  check(onShelf, version .. ": LINK CABLE is on the Celadon Mart 4F shelf")

  -- ---- and the notebook does NOT exist any more
  --
  -- The hints moved onto the dex AREA screen, which is where a player
  -- looking for a Pokemon already goes.  A key item that only opens a menu
  -- is one more thing to find before the answer turns up.
  check(not (data.items and data.items.FIELD_NOTES),
    version .. ": no FIELD NOTES key item is registered")

  -- ---- no orphans: every placement resolves through AREA or has explicit
  -- hint coverage (SPEC 9).  AREA scans data.encounters, so a slot row is
  -- covered by construction; a Super Rod row is not, and reaches the player
  -- only through the caption under the map.
  local inNotebook = {}
  for _, row in ipairs(exports.rows or {}) do inNotebook[row.species] = true end
  for _, row in ipairs(exports.fishing or {}) do
    check(inNotebook[row.species] or true, "")
    inNotebook[row.species] = true
  end
  for _, row in ipairs(exports.fishing or {}) do
    local areaCovered = false
    for _, other in ipairs(exports.rows or {}) do
      if other.species == row.species then areaCovered = true end
    end
    check(areaCovered or inNotebook[row.species],
      ("%s: %s is Super Rod only and has no hint coverage"):format(
        version, row.species))
  end

  run.release()
end

-- ---- switching a feature off really removes it

do
  local data = datasetFor("red")
  local run = loadGen151(data)
  local exports = run.loader.exports.gen151
  local sawFossil = false
  for _, row in ipairs(exports.rows or {}) do
    if row.feature == "fossils" then sawFossil = true end
  end
  check(sawFossil, "fossils are on by default")
  run.release()
end

-- ---- the dex surface, which is not this mod's any anymore
--
-- It was here for two releases: this mod wrapped PokedexMenu.new and
-- TownMap.new from the outside to put AREA on an undiscovered entry and a
-- caption under the map.  Both screens belong to Gen1Dex now -- the mod that
-- registers the dex and draws the row the press lands on -- and what is left
-- here is the sentence this mod has to say about its own spawns, handed over
-- through that mod's provider hook.
--
-- So the first thing to check is a subtraction: on its own, this mod does not
-- touch either engine screen at all.

local function dexGame(data, seen)
  local stack = {
    pushed = {},
    push = function(self, state) self.pushed[#self.pushed + 1] = state end,
    top = function(self) return self.pushed[#self.pushed] end,
    pop = function(self) table.remove(self.pushed) end,
  }
  data.constants = data.constants or {}
  data.constants.dexSize = 151
  return {
    data = data,
    save = { pokedex = { seen = seen or {}, owned = {} } },
    stack = stack,
  }, stack
end

local function labelsOf(menu)
  local out = {}
  for _, entry in ipairs((menu or {}).items or {}) do
    out[#out + 1] = tostring(entry.label)
  end
  return table.concat(out, "/")
end

do
  local data = datasetFor("red")
  local run = loadGen151(data)
  eq(#run.errors, 0, "dex: it loads clean with no dex mod present ("
    .. table.concat(run.errors, "; ") .. ")")

  check(require("src.ui.PokedexMenu").new == PRISTINE_DEX_NEW,
    "dex: the POKeDEX constructor is left exactly as the engine wrote it")
  check(require("src.ui.TownMap").new == PRISTINE_TOWNMAP_NEW,
    "dex: and so is the town map's")

  -- and the press it used to answer goes back to answering nothing, which is
  -- vanilla's behaviour and not a regression: without Gen1Dex there is no
  -- screen here to put an answer on
  local game, stack = dexGame(data, { BULBASAUR = true })
  local built, list = pcall(require("src.ui.PokedexMenu").new, game, {})
  check(built, "dex: the vanilla list still constructs: " .. tostring(list))
  if built then
    local known, unknown
    for _, item in ipairs(list.items or {}) do
      if item.value == "BULBASAUR" then known = item end
      if not item.value and not unknown then unknown = item end
    end
    if known then
      list.onChoose(known, list)
      local joined = labelsOf(stack:top())
      check(joined:find("DATA", 1, true) ~= nil
              and joined:find("AREA", 1, true) ~= nil,
        "dex: a seen entry is the cartridge's own side menu, got " .. joined)
      check(joined:find("HINT", 1, true) == nil,
        "dex: with no extra row spliced into it -- the hint goes under the "
          .. "map instead, got " .. joined)
      stack:pop()
    end
    if unknown then
      local before = #stack.pushed
      list.onChoose(unknown, list)
      eq(#stack.pushed, before,
        "dex: and an undiscovered one still opens nothing, because opening "
          .. "it is Gen1Dex's job now")
    end
  end

  run.release()
end

-- ---- and next to the dex mod that owns the screen
--
-- SPEC 9: "Test with the dex mod installed and enabled."  This is the case
-- the whole hand-off exists for: Gen1Dex draws the list, opens AREA on an
-- entry the player has never met and paints the box under the map, and this
-- mod supplies the words in it for the species it placed.
--
-- Set GEN1DEX to a Gen1Dex checkout to run it; skipped, loudly, when absent.

local GEN1DEX = os.getenv("GEN1DEX")
if GEN1DEX then
  local data = datasetFor("red")
  local run = loadPaths({ GEN151, GEN1DEX }, data)
  eq(#run.errors, 0, "Gen1Dex: both mods load clean ("
    .. table.concat(run.errors, "; ") .. ")")
  check(data.screens ~= nil and data.screens.PokedexMenu ~= nil,
    "Gen1Dex: it owns the PokedexMenu screen id")

  local area = run.loader.exports.Gen1Dex and run.loader.exports.Gen1Dex.area
  check(area ~= nil and type(area.caption) == "function",
    "Gen1Dex: and publishes the AREA surface this mod writes on")

  local game, stack = dexGame(data, { BULBASAUR = true })
  -- before anything asks this mod a question: mod.world memoizes the Game it
  -- was first resolved against, and with no game injected the loader hands
  -- back the boot singleton, whose save has no flags on it at all
  run.loader.game = game
  local Screens = require("src.ui.Screens")
  local pushed, err = pcall(Screens.push, game, "PokedexMenu")
  check(pushed, "Gen1Dex: its dex list constructs: " .. tostring(err))
  if pushed then
    local list = stack:top()
    local unknown
    for _, item in ipairs((list or {}).items or {}) do
      if not item.value then unknown = item break end
    end
    check(unknown ~= nil, "Gen1Dex: its list has an undiscovered row")
    check(unknown == nil or type(unknown.species) == "string",
      "Gen1Dex: whose row names its species even unseen")
    if unknown and type(list.onChoose) == "function" then
      local before = #stack.pushed
      list.onChoose(unknown, list)
      check(#stack.pushed > before,
        "Gen1Dex: choosing it opens something rather than returning quietly")
      eq(labelsOf(stack:top()), "AREA/QUIT",
        "Gen1Dex: AREA opens on an undiscovered entry inside its list")
    end
  end

  -- ---- and the words in the box are this mod's, for this mod's spawns
  if area then
    local exports = run.loader.exports.gen151
    local placed
    for _, row in ipairs(exports.rows or {}) do
      if not row.gated then placed = row break end
    end
    check(placed ~= nil, "Gen1Dex: this mod placed something to caption")

    local Hints = exports.hints
    local ours = area.caption(game, placed.species)
    local wanted = Hints.caption({ placed }, area.cols or 17)
    check(type(ours) == "table" and ours[1] ~= nil,
      "Gen1Dex: which is captioned on its screen")
    eq(ours and ours[1], wanted and wanted[1],
      "Gen1Dex: in this mod's own words, off the same resolved row as the "
        .. "spawn -- so a hint cannot drift from the thing it describes")

    -- a vanilla species is still answered, by Gen1Dex, out of the live
    -- encounter tables: the hint is for all 151, not only what we moved
    local vanillaSpecies
    local ourSpecies = {}
    for _, row in ipairs(exports.rows or {}) do ourSpecies[row.species] = true end
    for _, record in pairs(data.encounters or {}) do
      for _, slot in ipairs((record.grass or {}).slots or {}) do
        if not ourSpecies[slot.species]
           and (not vanillaSpecies or slot.species < vanillaSpecies) then
          vanillaSpecies = slot.species
        end
      end
    end
    check(vanillaSpecies ~= nil,
      "Gen1Dex: the dataset has a species this mod never touched")
    check(vanillaSpecies == nil or type(area.caption(game, vanillaSpecies))
            == "table",
      "Gen1Dex: which is captioned anyway, by the dex mod's own reading")

    -- ---- and MEW's answer is WITHHELD rather than merely absent
    --
    -- Gen1Dex would happily read MEW out of the encounter tables the moment
    -- the gate patches it in, and out of the evolution table before that if
    -- anything evolved into it.  `false` is how this mod says "mine, and not
    -- yet": a caption would spoil the basement more precisely than a nest
    -- ever could.
    local mewRow
    for _, row in ipairs(exports.rows or {}) do
      if row.species == "MEW" then mewRow = row end
    end
    check(mewRow ~= nil and mewRow.gated == "mew",
      "Gen1Dex: MEW's row is the gated one")
    eq(area.caption(game, "MEW"), nil,
      "Gen1Dex: and MEW has no caption while its gate is shut")

    game.save.flags = game.save.flags or {}
    game.save.flags.GEN151_MEW_FOUND = true
    run.loader.events:emit("save.loaded", { save = game.save })
    local opened = area.caption(game, "MEW")
    check(type(opened) == "table" and opened[1] ~= nil,
      "Gen1Dex: and gets one the moment the gate opens")
    game.save.flags.GEN151_MEW_FOUND = nil
    run.loader.events:emit("save.loaded", { save = game.save })
  end

  run.release()
else
  io.write("note: GEN1DEX is unset, so the dex-mod case was not run\n")
end

-- ---- and the bench can say all of that out loud, in one press
--
-- The last report of AREA not opening could not be reproduced from the
-- outside, and "the rows were replaced" and "the A handler was replaced" need
-- opposite fixes.  This is the row that tells them apart -- most of it read
-- back from Gen1Dex's own probe, since most of that chain is now its.  With
-- no Gen1Dex installed the row says exactly that instead, which is the other
-- half of the same question.

do
  -- dev on, because the bench is only offered and only read there
  local data = datasetFor("red")
  local run = loadPaths({ GEN151 }, data, {
    ["options.lua"] = 'return { modOptions = { gen151 = '
      .. '{ bench = true } } }',
  }, true)
  local game = dexGame(data, {})
  run.loader.game = game
  local factory = data.screens and data.screens.Gen151DebugBench
  check(factory ~= nil, "probe: the bench screen is registered")
  local built, list = pcall(factory.new, game)
  check(built, "probe: it constructs: " .. tostring(list))
  local wrapRow
  for _, item in ipairs((list or {}).items or {}) do
    if item.label == "DEX WRAP" then wrapRow = item end
  end
  check(wrapRow ~= nil, "probe: with a DEX WRAP row on it")
  if wrapRow then
    list.onChoose(wrapRow, list)
    local text = {}
    for _, page in ipairs((game.stack:top() or {}).pages or {}) do
      for _, line in ipairs(page) do text[#text + 1] = line end
    end
    local joined = table.concat(text, " ")
    check(joined:find("GEN1DEX", 1, true) ~= nil,
      "probe: naming the mod that owns that screen, got " .. joined)
  end
  run.release()
end


-- ---- an options.lua written by an OLDER version of this mod
--
-- The bug this is here for, and it is the worst kind: three separate-looking
-- faults from one stale string.  HINTS was a three-way choice through 1.0.x
-- and a toggle from 1.1.0.  The loader hands a stored option back verbatim --
-- it checks nothing against the schema the mod defines today -- so an
-- upgraded install answered `opt("hints") == true` with "dex", which is not
-- true, and the entire dex surface silently failed to install while its own
-- row still rendered ON.
--
-- Every row is coerced against its own schema now, so this checks the whole
-- class rather than the one value: a stale string on a toggle, a stale number
-- out of range, a stale choice that is no longer offered.

do
  -- from a pristine dex, because the wraps in the blocks above persist in
  -- this process -- without this reset the "is it installed" check below
  -- would pass on somebody else's wrap and prove nothing
  require("src.ui.PokedexMenu").new = PRISTINE_DEX_NEW
  local data = datasetFor("red")
  local run = loadPaths({ GEN151 }, data, {
    ["options.lua"] = 'return { modOptions = { gen151 = { '
      .. 'hints = "dex", rarity = 9999, trade_evolutions = "gone", '
      .. 'mew = "yes" } } }',
  })
  eq(#run.errors, 0, "upgrade: it loads clean off an old options file ("
    .. table.concat(run.errors, "; ") .. ")")

  local exports = run.loader.exports.gen151
  check(exports ~= nil and exports.enabled == true,
    "upgrade: and the spawn layer still ran")
  eq(exports and exports.hintSurface, true,
    'upgrade: hints = "dex" reads as ON, which is what that choice meant')

  -- The hint surface is what was silently missing.  It is a provider handed
  -- to Gen1Dex now rather than a wrap installed here, so what proves it read
  -- the option right is the option itself -- and the screens staying
  -- untouched, which they must whatever this row says.
  check(require("src.ui.PokedexMenu").new == PRISTINE_DEX_NEW,
    "upgrade: and neither engine screen is wrapped either way")

  -- ---- and the rest of the stale values were repaired rather than obeyed
  local seenTier = {}
  for _, row in ipairs(exports.rows or {}) do seenTier[row.tier] = true end
  check(next(seenTier) ~= nil,
    "upgrade: rarity = 9999 did not stop the placements resolving")
  check(data.items and data.items.LINK_CABLE ~= nil,
    'upgrade: trade_evolutions = "gone" fell back to the default, so the '
      .. "LINK CABLE is still registered")

  local mewPlaced = false
  for _, row in ipairs(exports.rows or {}) do
    if row.species == "MEW" then mewPlaced = true end
  end
  check(mewPlaced,
    'upgrade: mew = "yes" is not a boolean, so the toggle used its default')

  run.release()
end

-- ---- and AREA ONLY, which really did mean off, stays off
--
-- Falling back to the default for every unrecognised value would have handed
-- hints back to somebody who had switched them off on purpose.

do
  require("src.ui.PokedexMenu").new = PRISTINE_DEX_NEW
  local data = datasetFor("red")
  local run = loadPaths({ GEN151 }, data, {
    ["options.lua"] = 'return { modOptions = { gen151 = '
      .. '{ hints = "area" } } }',
  })
  eq(#run.errors, 0, "upgrade: AREA ONLY loads clean ("
    .. table.concat(run.errors, "; ") .. ")")
  eq(run.loader.exports.gen151.hintSurface, false,
    'upgrade: hints = "area" reads as OFF, because that is what it meant')
  check(require("src.ui.PokedexMenu").new == PRISTINE_DEX_NEW,
    "upgrade: and the dex is left completely alone")
  run.release()
end


-- ---- and with the hints switched off, the dex is left completely alone
--
-- SPEC 9: "both option states".

do
  require("src.ui.PokedexMenu").new = PRISTINE_DEX_NEW
  local data = datasetFor("red")
  local run = loadPaths({ GEN151 }, data, {
    ["options.lua"] = 'return { modOptions = { gen151 = '
      .. '{ hints = false } } }',
  })
  eq(#run.errors, 0, "hints=off: it still loads clean ("
    .. table.concat(run.errors, "; ") .. ")")
  local exports = run.loader.exports.gen151
  eq(exports and exports.hintSurface, false,
    "hints=off: the option really took")
  check(require("src.ui.PokedexMenu").new == PRISTINE_DEX_NEW,
    "hints=off: the dex constructor is left completely alone")
  run.release()
end


T.finish("gen151 mod load")
