-- The roll-layer suite (SPEC 9, SPEC 11 step 3).
--
-- Driven against the engine's OWN src/world/Encounter.lua, not a copy of it:
-- the whole point of stage one is that it is the vanilla function, so a test
-- that reimplemented the vanilla roll would prove nothing.  Encounter.lua and
-- FieldDefaults.lua are pure Lua with no love.* dependency, which is what
-- makes that possible headlessly.
--
--   GEN1RECOMP=/path/to/gen1recomp lua tests/roll_test.lua
--
-- Vanilla tables come from tests/fixtures/vanilla.lua, generated by
-- tools/gapset.py out of the pret disassembly -- the same source the engine's
-- own extractor parses.

local ENGINE = os.getenv("GEN1RECOMP") or "../gen1recomp"
package.path = table.concat({
  ENGINE .. "/?.lua",
  ENGINE .. "/?/init.lua",
  "./?.lua",
  "./?/init.lua",
  package.path,
}, ";")

local ok, Encounter = pcall(require, "src.world.Encounter")
if not ok then
  io.stderr:write("cannot reach the engine tree at " .. ENGINE ..
    "\nset GEN1RECOMP to a gen1recomp checkout\n" .. tostring(Encounter) .. "\n")
  os.exit(1)
end
local FieldDefaults = require("src.world.FieldDefaults")
local Roll = dofile("roll.lua")
local Rarity = dofile("rarity.lua")

local vanilla = dofile("tests/fixtures/vanilla.lua")

-- ------------------------------------------------------------------ harness

local failures, checks = 0, 0

local function check(cond, fmt, ...)
  checks = checks + 1
  if cond then return true end
  failures = failures + 1
  io.write("FAIL: " .. string.format(fmt, ...) .. "\n")
  return false
end

local function eq(a, b, fmt, ...)
  return check(a == b, string.format(fmt, ...) ..
    (" (got %s, want %s)"):format(tostring(a), tostring(b)))
end

-- A deterministic RNG with the engine's love.math.random(min, max) shape, plus
-- a tape of every draw it served.  Comparing tapes is how "identical RNG draw
-- for RNG draw" stops being a figure of speech.
--
-- L'Ecuyer's combined multiple-recursive generator: two prime-modulus streams,
-- differenced.  Portable arithmetic only -- every product stays under 2^53, so
-- it is exact on LuaJIT's doubles as well as on 5.4's integers, and the engine
-- targets LuaJIT, which has no 5.4 bitwise operators to reach for instead.
--
-- It was a single power-of-two LCG (`state = 1103515245 * state + 12345 mod
-- 2^31`, read from the top bits) and that quietly broke the two SHARE
-- assertions below.  Not through the low bits the old comment here worried
-- about -- through the lattice.  Successive outputs of a power-of-two LCG lie
-- on a coarse lattice, and every one of those assertions asks a CONDITIONAL
-- question: given that the previous draw was small enough to produce an
-- encounter (20/256 on Route 4), how is the next one distributed?  Small
-- output followed by small output turned out to be far more likely than
-- chance, so the measured substitution rate came out 35% above the weight that
-- produced it -- 5.79% for a 4.30% tier -- and the suite reported the roll
-- layer as broken.  It was not: the same experiment through math.random lands
-- on 4.30%, and so does this generator, whose mean over twenty seeds is 1.007
-- times the configured share.
--
-- The moral is in the assertions rather than in the generator: a statistical
-- test drawing from the same stream as the thing it measures is measuring both
-- of them.
local function makeRng(seed)
  -- both streams need a non-zero start inside their own modulus
  local s1 = seed % 2147483562 + 1
  local s2 = (seed * 7919) % 2147483398 + 1
  local self = { draws = 0, tape = {} }
  function self.next(min, max)
    s1 = (40014 * s1) % 2147483563
    s2 = (40692 * s2) % 2147483399
    local z = (s1 - s2) % 2147483562
    local value = min + math.floor(z / 2147483562 * (max - min + 1))
    if value > max then value = max end
    self.draws = self.draws + 1
    self.tape[self.draws] = value
    return value
  end
  return self
end

local function tapesEqual(a, b)
  if #a ~= #b then return false, ("draw counts differ: %d vs %d"):format(#a, #b) end
  for i = 1, #a do
    if a[i] ~= b[i] then
      return false, ("draw %d differs: %s vs %s"):format(i, a[i], b[i])
    end
  end
  return true
end

-- ------------------------------------------------------------------ fixtures

-- the engine's own bucket list, read from the engine
local BUCKETS = FieldDefaults.CONSTANTS.encounterBuckets

local function deepCopy(value)
  if type(value) ~= "table" then return value end
  local copy = {}
  for k, v in pairs(value) do copy[k] = deepCopy(v) end
  return copy
end

-- the merged shape the engine hands the chain: for grass/indoor the whole
-- record, for water the synthetic { grass = <water table> }
local function defFor(mapId, terrain, version)
  local record = vanilla.versions[version or "red"].encounters[mapId]
  if not record then return nil end
  if terrain == "water" then
    if not record.water then return nil end
    return { grass = deepCopy(record.water) }
  end
  if not record.grass then return nil end
  return deepCopy(record)
end

local function vanillaLink(def, ctx) return Encounter.roll(def, ctx.rng) end

local ROLLS = 200000

-- ---------------------------------------------------- 1. zero-rarity identity
--
-- SPEC 9: "Seed the RNG, roll each map 10^6 times with Gen151 rarities at 0,
-- and assert the species histogram matches a clean install exactly."  The
-- stronger form is asserted here: the RNG TAPE matches, so the layer is proven
-- to consume no draws at all rather than to consume some and land on the same
-- distribution by luck.

local function histogram(fn, seed)
  local rng = makeRng(seed)
  local counts, encounters = {}, 0
  for _ = 1, ROLLS do
    local enc = fn(rng)
    if enc then
      encounters = encounters + 1
      counts[enc.species] = (counts[enc.species] or 0) + 1
      counts["#level:" .. enc.level] = (counts["#level:" .. enc.level] or 0) + 1
    end
  end
  return counts, encounters, rng.tape
end

local function sameHistogram(a, b)
  for key, value in pairs(a) do
    if b[key] ~= value then
      return false, ("%s: %d vs %s"):format(key, value, tostring(b[key]))
    end
  end
  for key in pairs(b) do
    if a[key] == nil then return false, key .. ": missing on the left" end
  end
  return true
end

local IDENTITY_MAPS = {
  { "ROUTE_1", "grass" }, { "ROUTE_4", "grass" }, { "VIRIDIAN_FOREST", "grass" },
  { "MT_MOON_1F", "grass" }, { "CERULEAN_CAVE_1F", "grass" },
  { "POKEMON_MANSION_1F", "grass" }, { "VICTORY_ROAD_2F", "grass" },
  { "SEAFOAM_ISLANDS_B4F", "grass" }, { "SAFARI_ZONE_CENTER", "grass" },
  { "ROUTE_21", "water" }, { "ROUTE_19", "water" },
}

do
  for _, case in ipairs(IDENTITY_MAPS) do
    local mapId, terrain = case[1], case[2]
    local def = defFor(mapId, terrain)
    if check(def ~= nil, "fixture has %s %s", mapId, terrain) then
      local clean, cleanCount, cleanTape = histogram(function(rng)
        return Encounter.roll(def, rng.next)
      end, 1234)

      -- the same map with Gen151 installed and every rarity at zero
      local layer = Roll.new()
      layer:setVanillaCount(mapId, terrain, #def.grass.slots)
      layer:add(mapId, terrain,
        { species = "GEN151_SENTINEL", level = 99, weight = 0 })
      local patched = deepCopy(def)
      patched.grass.slots[#patched.grass.slots + 1] =
        { level = 99, species = "GEN151_SENTINEL" }
      local ctx = { mapId = mapId, terrain = terrain }

      local got, gotCount, gotTape = histogram(function(rng)
        ctx.rng = rng.next
        return layer:roll(vanillaLink, patched, ctx, rng.next)
      end, 1234)

      local same, why = sameHistogram(clean, got)
      check(same, "%s %s: histogram differs at zero rarity: %s",
        mapId, terrain, tostring(why))
      eq(gotCount, cleanCount, "%s %s: encounter count", mapId, terrain)
      local tapeOk, tapeWhy = tapesEqual(cleanTape, gotTape)
      check(tapeOk, "%s %s: RNG tape differs at zero rarity: %s",
        mapId, terrain, tostring(tapeWhy))
      eq(got.GEN151_SENTINEL, nil,
        "%s %s: appended slot is unreachable from stage one", mapId, terrain)
    end
  end
end

-- --------------------------------------------- 2. a hostile foreign bucket list
--
-- The failure this whole architecture exists to avoid: another mod appends a
-- slot and ships its own `buckets`.  A layer that read them would fall off the
-- end of the table and return "no encounter" with no error anywhere.

do
  local mapId, terrain = "ROUTE_4", "grass"
  local def = defFor(mapId, terrain)
  local clean, cleanCount = histogram(function(rng)
    return Encounter.roll(def, rng.next)
  end, 99)

  local hostile = deepCopy(def)
  hostile.grass.slots[11] = { level = 40, species = "OTHER_MOD_MON" }
  -- The exact silent failure SPEC 3b describes: an 11-slot table whose bucket
  -- list neither matches the slot count nor ends at 256.  Every pick at or
  -- above the last threshold falls off the end of the loop and comes back as
  -- "no encounter", with nothing logged anywhere.
  hostile.grass.buckets = { 51, 102, 141 }

  local layer = Roll.new()
  layer:setVanillaCount(mapId, terrain, 10)
  local ctx = { mapId = mapId, terrain = terrain }
  local got, gotCount = histogram(function(rng)
    ctx.rng = rng.next
    return layer:roll(vanillaLink, hostile, ctx, rng.next)
  end, 99)

  local same, why = sameHistogram(clean, got)
  check(same, "foreign buckets changed the distribution: %s", tostring(why))
  eq(gotCount, cleanCount, "foreign buckets changed the encounter count")

  -- ...and the same table WITHOUT the layer really is broken, so the
  -- assertion above is testing something.
  local _, naiveCount = histogram(function(rng)
    return Encounter.roll(hostile, rng.next)
  end, 99)
  check(naiveCount < cleanCount * 0.9,
    "the hostile bucket list should silently drop encounters from an "
      .. "unprotected roll (got %d of %d), so this test no longer proves "
      .. "anything", naiveCount, cleanCount)
end

-- ------------------------------------------------- 3. rate is never disturbed
--
-- Encounter RATE is the one thing the divergence budget does not cover.  At
-- ZERO rarity the count is identical draw for draw (asserted in 1 above).
-- Once a rarity is nonzero, stage two consumes a draw per encounter, so the
-- stream necessarily shifts and the identical-count claim becomes a
-- statistical one instead: the rate is unchanged, so over 200k rolls the two
-- counts must agree to within sampling noise.  Three standard deviations of a
-- binomial at these sizes is well under 1%.
do
  for _, case in ipairs(IDENTITY_MAPS) do
    local mapId, terrain = case[1], case[2]
    local def = defFor(mapId, terrain)
    if def then
      local _, cleanCount = histogram(function(rng)
        return Encounter.roll(def, rng.next)
      end, 4242)

      local layer = Roll.new()
      layer:setVanillaCount(mapId, terrain, #def.grass.slots)
      layer:add(mapId, terrain, { species = "AAA", level = 20,
                                  weight = Rarity.TIERS.UNCOMMON })
      layer:add(mapId, terrain, { species = "BBB", level = 20,
                                  weight = Rarity.TIERS.VERY_RARE })
      local ctx = { mapId = mapId, terrain = terrain }
      local _, gotCount = histogram(function(rng)
        ctx.rng = rng.next
        return layer:roll(vanillaLink, def, ctx, rng.next)
      end, 4242)
      local p = cleanCount / ROLLS
      local sigma = math.sqrt(ROLLS * p * (1 - p))
      check(math.abs(gotCount - cleanCount) < 4 * sigma,
        "%s %s: encounter rate moved: %d vs %d (4 sigma = %.0f)",
        mapId, terrain, gotCount, cleanCount, 4 * sigma)
    end
  end
end

-- ----------------------------------------- 4. only the intended species gains
--
-- Probability is conserved: the added species take exactly their configured
-- share, every vanilla species loses share strictly in proportion, and none of
-- them falls below the floor that proportion implies.

do
  local mapId, terrain = "ROUTE_4", "grass"
  local def = defFor(mapId, terrain)
  local clean, cleanCount = histogram(function(rng)
    return Encounter.roll(def, rng.next)
  end, 777)

  local layer = Roll.new()
  layer:setVanillaCount(mapId, terrain, 10)
  local weight = Rarity.TIERS.UNCOMMON
  layer:add(mapId, terrain, { species = "SANDSHREW", level = 10,
                              weight = weight })
  local ctx = { mapId = mapId, terrain = terrain }
  local got, gotCount = histogram(function(rng)
    ctx.rng = rng.next
    return layer:roll(vanillaLink, def, ctx, rng.next)
  end, 777)

  local p = cleanCount / ROLLS
  local sigma = math.sqrt(ROLLS * p * (1 - p))
  check(math.abs(gotCount - cleanCount) < 4 * sigma,
    "substitution changed the encounter count: %d vs %d", gotCount, cleanCount)

  -- 4 sigma of the binomial the substitution draw actually is, rather than a
  -- flat percentage: at 4.3% of ~16500 encounters one sigma is 25 hits, so a
  -- flat 10% band was 2.6 sigma wide and would flake on a seed nobody chose
  local share = weight / Roll.RARITY_SCALE
  local added = got.SANDSHREW or 0
  local expected = gotCount * share
  local addedSigma = math.sqrt(gotCount * share * (1 - share))
  check(math.abs(added - expected) < 4 * addedSigma,
    "added species share: got %d, expected about %.0f (4 sigma = %.0f)",
    added, expected, 4 * addedSigma)

  for species, count in pairs(clean) do
    if species:sub(1, 1) ~= "#" then
      local after = got[species] or 0
      local floor = count * (1 - share)
      check(after >= floor * 0.90,
        "%s fell below its floor: %d, floor about %.0f", species, after, floor)
      check(after <= count * 1.02,
        "%s gained share it was not meant to: %d > %d", species, after, count)
    end
  end
end

-- -------------------------------------------- 5. an untouched map is untouched

do
  local def = defFor("ROUTE_2", "grass")
  local layer = Roll.new()
  layer:setVanillaCount("ROUTE_4", "grass", 10)
  layer:add("ROUTE_4", "grass", { species = "SANDSHREW", level = 10,
                                  weight = Rarity.TIERS.UNCOMMON })
  local clean, cleanCount, cleanTape = histogram(function(rng)
    return Encounter.roll(def, rng.next)
  end, 31337)
  local ctx = { mapId = "ROUTE_2", terrain = "grass" }
  local got, gotCount, gotTape = histogram(function(rng)
    ctx.rng = rng.next
    return layer:roll(vanillaLink, def, ctx, rng.next)
  end, 31337)
  local same = sameHistogram(clean, got)
  check(same, "an unplaced map's distribution moved")
  eq(gotCount, cleanCount, "an unplaced map's encounter count moved")
  check((tapesEqual(cleanTape, gotTape)), "an unplaced map consumed extra draws")
end

-- ----------------------------------------------- 6. the gated row stays hidden

do
  local mapId, terrain = "CERULEAN_CAVE_1F", "grass"
  local def = defFor(mapId, terrain)
  local unlocked = false
  local layer = Roll.new()
  layer:setVanillaCount(mapId, terrain, #def.grass.slots)
  layer:add(mapId, terrain, { species = "MEW", level = 60,
                              weight = Rarity.TIERS.VERY_RARE,
                              active = function() return unlocked end })
  local ctx = { mapId = mapId, terrain = terrain }

  local locked, _, lockedTape = histogram(function(rng)
    ctx.rng = rng.next
    return layer:roll(vanillaLink, def, ctx, rng.next)
  end, 5150)
  eq(locked.MEW, nil, "a locked row must never be rolled")
  local _, _, cleanTape = histogram(function(rng)
    return Encounter.roll(def, rng.next)
  end, 5150)
  check((tapesEqual(cleanTape, lockedTape)),
    "a locked row must not consume a draw either")

  unlocked = true
  local open = histogram(function(rng)
    ctx.rng = rng.next
    return layer:roll(vanillaLink, def, ctx, rng.next)
  end, 5150)
  check((open.MEW or 0) > 0, "an unlocked row must be reachable")
end

-- --------------------------------------------------- 7. the Super Rod peer

do
  local rows = { { level = 5, species = "MAGIKARP" },
                 { level = 10, species = "MAGIKARP" },
                 { level = 10, species = "DRATINI" },
                 { level = 15, species = "DRATINI" } }
  -- the engine's rejection loop, verbatim from OverworldController
  local function fishVanilla(rng)
    return function()
      while true do
        local r = rng(0, 255)
        if r % 2 == 1 then return nil end
        local pick = math.floor(r / 2) % 4
        if pick < #rows then
          return { species = rows[pick + 1].species, level = rows[pick + 1].level }
        end
      end
    end
  end

  local layer = Roll.new()
  layer:addFishing("SAFARI_ZONE_EAST", "SUPER_ROD",
    { species = "OMANYTE", level = 30, weight = Rarity.TIERS.RARE })

  local rng = makeRng(2024)
  local bites, omanyte = 0, 0
  for _ = 1, ROLLS do
    local enc = layer:fish(function() return fishVanilla(rng.next)() end,
      "SUPER_ROD", "SAFARI_ZONE_EAST", rows, rng.next)
    if enc then
      bites = bites + 1
      if enc.species == "OMANYTE" then omanyte = omanyte + 1 end
    end
  end

  local rngB = makeRng(2024)
  local cleanBites = 0
  for _ = 1, ROLLS do
    if fishVanilla(rngB.next)() then cleanBites = cleanBites + 1 end
  end
  -- as in 3 above: substitution consumes a draw, so the streams diverge and
  -- the bite odds claim is statistical rather than draw-for-draw
  local pBite = cleanBites / ROLLS
  local sigmaBite = math.sqrt(ROLLS * pBite * (1 - pBite))
  check(math.abs(bites - cleanBites) < 4 * sigmaBite,
    "Super Rod bite odds moved: %d vs %d (4 sigma = %.0f)",
    bites, cleanBites, 4 * sigmaBite)
  local rodShare = Rarity.TIERS.RARE / Roll.RARITY_SCALE
  local expected = bites * rodShare
  local rodSigma = math.sqrt(bites * rodShare * (1 - rodShare))
  check(math.abs(omanyte - expected) < 4 * rodSigma,
    "Super Rod substitution share: got %d, expected about %.0f "
      .. "(4 sigma = %.0f)", omanyte, expected, 4 * rodSigma)
end

-- ---------------------------------------------------------------------- done

io.write(("\nroll_test: %d checks, %d failures\n"):format(checks, failures))
os.exit(failures == 0 and 0 or 1)
