-- Render SPOILERS.md from placements.lua, through the SAME resolver the mod
-- runs (SPEC 8: placements.lua drives the encounter patches AND the hints AND
-- the spoiler table, so none of the three can disagree with the other two).
--
--   luajit tools/dump_placements.lua > SPOILERS.md
--
-- The vanilla tables come from tests/fixtures/vanilla.lua, generated by
-- tools/gapset.py out of the pret disassembly, so the levels printed here are
-- the levels the band rule actually lands on, per version, rather than a
-- description of what it is supposed to land on.

package.path = "./?.lua;./?/init.lua;" .. package.path

local Placements = dofile("placements.lua")
local Build = dofile("build.lua")
local Rarity = dofile("rarity.lua")
local Hints = dofile("hints.lua")
local vanilla = dofile("tests/fixtures/vanilla.lua")

local VERSIONS = { "red", "blue", "yellow" }
local LABEL = { red = "Red", blue = "Blue", yellow = "Yellow" }

local function sourceFor(version)
  local set = vanilla.versions[version]
  return {
    eachEncounter = function()
      return pairs(set.encounters)
    end,
    encounter = function(id) return set.encounters[id] end,
    eachPokemon = function() return pairs(set.pokemon) end,
    field = function(key)
      if key == "fishing" then
        return {
          OLD_ROD = { always = { species = "MAGIKARP", level = 5 } },
          GOOD_ROD = { pool = set.goodRod },
          SUPER_ROD = { perMap = "superRod" },
        }
      end
      if key == "superRod" then return set.superRod end
      return nil
    end,
  }
end

local ALL_ON = {
  exclusives = true, gifts = true, fossils = true, snorlax = true,
  mew = true,
}

local function levels(row)
  return Hints.levelRange(row.levels) or "--"
end

local function methodOf(row)
  if row.rod then return "Super Rod" end
  return row.method == "water" and "surf" or "grass"
end

io.write([[
# Gen151 -- SPOILERS

The whole placement table, for people who want it.  Nothing below is a
surprise the mod intends to keep; the FIELD NOTES item in the bag tells the
player the same things one species at a time, and the dex AREA screen lights
up every map in here on its own.

**GENERATED** by `tools/dump_placements.lua` from `placements.lua`, through
the same resolver the mod runs, so a row here cannot disagree with the spawn
it describes.  Every option is switched on for this dump, including the Mew
event, which ships off by default.

A species appears on a version only when that version has no renewable source
for it.  That is why the same row is present on one cartridge and absent on
another: Ekans is already in Red's grass, so Gen151 does nothing about Ekans
on Red.

Rarity is the share of the ENCOUNTERS on that map, not of the steps taken.
The encounter rate itself is never touched, so these numbers change what jumps
you, never how often.

]])

for _, tier in ipairs(Rarity.ORDER) do
  io.write(("- **%s** -- about %.2f%% of a map's encounters (%s)\n"):format(
    tier:gsub("_", " "):lower(),
    Rarity.TIERS[tier] / 100, Rarity.LABELS[tier]))
end
io.write("\n")

for _, version in ipairs(VERSIONS) do
  local resolved = Build.resolve(Placements, sourceFor(version), {
    rarity = Rarity, multiplier = 100, features = ALL_ON,
  })

  local rows = {}
  for _, row in ipairs(resolved.rows) do rows[#rows + 1] = row end
  for _, row in ipairs(resolved.fishing) do rows[#rows + 1] = row end
  table.sort(rows, function(a, b)
    if a.species ~= b.species then return a.species < b.species end
    return a.map < b.map
  end)

  local species = {}
  local seen = {}
  for _, row in ipairs(rows) do
    if not seen[row.species] then
      seen[row.species] = true
      species[#species + 1] = row.species
    end
  end

  io.write(("## %s -- %d species, %d rows\n\n"):format(
    LABEL[version], #species, #rows))
  io.write("| Species | Where | How | Levels | Rarity | Behind | Why |\n")
  io.write("|---|---|---|---|---|---|---|\n")
  for _, row in ipairs(rows) do
    io.write(("| %s | %s | %s | %s | %s | %s | %s |\n"):format(
      row.species,
      Hints.mapName(row.map),
      methodOf(row),
      levels(row),
      Rarity.LABELS[row.tier] or row.tier,
      row.gate or "nothing",
      (row.why or ""):gsub("|", "/")))
  end
  io.write("\n")
end

io.write([[
## Not placed, on purpose

**Articuno, Zapdos, Moltres and Mewtwo** keep their vanilla statics, untouched.
No respawn, no wild slot, no option to add one.  They are the sole exception to
the rule that everything Gen151 touches must be renewable, and the practical
consequence is that the soft-reset-before-the-catch discipline stays the way to
handle a bad outcome, exactly as in vanilla.

**Alakazam, Machamp, Golem and Gengar** are not spawns.  Their pre-evolutions
are already in the vanilla grass on every version; what was missing was the
trade.  A LINK CABLE from Celadon Department Store 4F -- the same shelf and the
same 2100 as the evolution stones -- runs exactly one of them, and breaks.

**Every Set C species** -- Ivysaur, Venusaur, Charmeleon, Charizard, Wartortle,
Blastoise, Ninetales, Persian, Sandslash, Arbok, Weepinbell, Victreebel,
Omastar, Kabutops, Raichu, Weezing, Beedrill, Kakuna, Gloom, Vileplume,
Primeape, Arcanine, Vaporeon, Jolteon, Flareon -- follows from a placement
above rather than getting one of its own.  Fixing the parent fixes the child,
and a wild Venusaur on a route where Bulbasaur lives would read as an error.
]])
